//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFLinqAnalyzer.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SourceFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SourceFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFLinqAnalyzer.Test.SourceFiles", typeof(SourceFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///
        ///        public string FooBar
        ///        {
        ///            get { return this.Foo + &quot; &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ001_ClassWithReadOnlyProperty_ReferencedInUnqualifiedDbContext {
            get {
                return ResourceManager.GetString("EFLINQ001_ClassWithReadOnlyProperty_ReferencedInUnqualifiedDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : System.Data.Entity.DbContext
        ///    {
        ///        public System.Data.Entity.DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///
        ///        public string FooBar
        ///        {
        ///            get { return thi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ001_ClassWithReadOnlyPropertyAndExprBodiedMember_ReferencedInFullyQualifiedDbContext {
            get {
                return ResourceManager.GetString("EFLINQ001_ClassWithReadOnlyPropertyAndExprBodiedMember_ReferencedInFullyQualified" +
                        "DbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///
        ///        public string FooBar
        ///        {
        ///            get { return this.Foo + &quot; &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ001_ClassWithReadOnlyPropertyAndExprBodiedMember_ReferencedInUnqualifiedDbContext {
            get {
                return ResourceManager.GetString("EFLINQ001_ClassWithReadOnlyPropertyAndExprBodiedMember_ReferencedInUnqualifiedDbC" +
                        "ontext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///
        ///        public string FooBar
        ///        {
        ///            get { return this.Foo + &quot; &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ002_LinqSelect {
            get {
                return ResourceManager.GetString("EFLINQ002_LinqSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///
        ///        public string FooBar
        ///        {
        ///            get { return this.Foo + &quot; &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ002_LinqWhere {
            get {
                return ResourceManager.GetString("EFLINQ002_LinqWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        static bool FooIsBar(string foo, string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ003_LinqSelect {
            get {
                return ResourceManager.GetString("EFLINQ003_LinqSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        static bool FooIsBar(string foo, string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ003_LinqSelect_IndirectDbSet {
            get {
                return ResourceManager.GetString("EFLINQ003_LinqSelect_IndirectDbSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        static bool FooIsBar(string foo, string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ003_LinqSelect_IndirectDbSetFromMethod {
            get {
                return ResourceManager.GetString("EFLINQ003_LinqSelect_IndirectDbSetFromMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyBaseContext : DbContext
        ///    {
        ///    }
        ///
        ///    public class MyContext : MyBaseContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ003_LinqSelect_NonDirectDbContextDescendant {
            get {
                return ResourceManager.GetString("EFLINQ003_LinqSelect_NonDirectDbContextDescendant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///using System.Data.Entity.Spatial;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public DateTime At { get; set; }
        ///        public double ADouble { get; set; }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ003_LinqSelect_ValidMethods {
            get {
                return ResourceManager.GetString("EFLINQ003_LinqSelect_ValidMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        static bool FooIsBar(string foo, string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ003_LinqWhere {
            get {
                return ResourceManager.GetString("EFLINQ003_LinqWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Linq.Expressions;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        static  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ003_LinqWhere_IndirectLambdaFromLocalVar {
            get {
                return ResourceManager.GetString("EFLINQ003_LinqWhere_IndirectLambdaFromLocalVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        public static void Main(string [] args) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ004_LinqSelect {
            get {
                return ResourceManager.GetString("EFLINQ004_LinqSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        public static void Main(string [] args) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ004_LinqWhere {
            get {
                return ResourceManager.GetString("EFLINQ004_LinqWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///
        ///        public string FooBar
        ///        {
        ///            get { return this.Foo + &quot; &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ005_LinqSelect {
            get {
                return ResourceManager.GetString("EFLINQ005_LinqSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///
        ///        public string FooBar
        ///        {
        ///            get { return this.Foo + &quot; &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ005_LinqWhere {
            get {
                return ResourceManager.GetString("EFLINQ005_LinqWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        static bool FooIsBar(string foo, string [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ006_LinqSelect_IndirectDbSetFromMethodThruIQueryableFacade {
            get {
                return ResourceManager.GetString("EFLINQ006_LinqSelect_IndirectDbSetFromMethodThruIQueryableFacade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///
        ///        public DbSet&lt;Sprocket&gt; Sprockets { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public int Id { get; set; }
        ///        public string Foo { get; set; }
        ///        public string Bar {  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ008_LinqWhere {
            get {
                return ResourceManager.GetString("EFLINQ008_LinqWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///
        ///        public DbSet&lt;Sprocket&gt; Sprockets { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public int Id { get; set; }
        ///        public string Foo { get; set; }
        ///        public string Bar {  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ008_LinqWhere_LegitimateUse {
            get {
                return ResourceManager.GetString("EFLINQ008_LinqWhere_LegitimateUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///using System.Data.Entity;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;NotAThing&gt; NotThings { get; set; }
        ///
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///
        ///        public DbSet&lt;Sprocket&gt; Sprockets { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public int Id { get; set; }
        ///        pu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ010_LinqWhere {
            get {
                return ResourceManager.GetString("EFLINQ010_LinqWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Linq;
        ///using System.Data.Entity;
        ///
        ///namespace UnitTest
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public int Id { get; set; }
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        public static void Main(string[] args)
        ///        {
        ///            using (var context = new MyContext())
        ///            {
        ///                var item [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ011_LinqSelect {
            get {
                return ResourceManager.GetString("EFLINQ011_LinqSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System.Linq;
        ///using System.Data.Entity;
        ///
        ///namespace UnitTest
        ///{
        ///    public class MyContext : DbContext
        ///    {
        ///        public DbSet&lt;Thing&gt; Things { get; set; }
        ///    }
        ///
        ///    public class Thing
        ///    {
        ///        public int Id { get; set; }
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///    }
        ///
        ///    class Program
        ///    {
        ///        static IQueryable&lt;Thing&gt; GetThings(MyContext context)
        ///        {
        ///            return context.Things;
        ///        }
        ///
        ///        public static void [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EFLINQ012_LinqSelect {
            get {
                return ResourceManager.GetString("EFLINQ012_LinqSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    class TypeName
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///
        ///        public string FooBar
        ///        {
        ///            get { return this.Foo + &quot; &quot; + this.Bar; }
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string NonEFClassWithReadOnlyProperty {
            get {
                return ResourceManager.GetString("NonEFClassWithReadOnlyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Diagnostics;
        ///
        ///namespace ConsoleApplication1
        ///{
        ///    class TypeName
        ///    {
        ///        public string Foo { get; set; }
        ///        public string Bar { get; set; }
        ///
        ///        public string FooBar =&gt; this.Foo + &quot; &quot; + this.Bar; 
        ///    }
        ///}.
        /// </summary>
        internal static string NonEFClassWithReadOnlyPropertyExprMember {
            get {
                return ResourceManager.GetString("NonEFClassWithReadOnlyPropertyExprMember", resourceCulture);
            }
        }
    }
}
