//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFLinqAnalyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EFLinqAnalyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only properties should not participate in IQueryable LINQ expressions (where clauses, joins or projections). Such properties will cause the EF LINQ provider to throw a NotSupportedException as they are not translatable to SQL.
        /// </summary>
        internal static string EFLINQ001_DESC {
            get {
                return ResourceManager.GetString("EFLINQ001_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; in type &apos;{1}&apos; not translatable in LINQ to Entities.
        /// </summary>
        internal static string EFLINQ001_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ001_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only EF code first property.
        /// </summary>
        internal static string EFLINQ001_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ001_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only properties are not translatable to SQL in LINQ to Entities and will cause a NotSupportedException to be thrown by a EF LINQ provider.
        /// </summary>
        internal static string EFLINQ002_DESC {
            get {
                return ResourceManager.GetString("EFLINQ002_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only property &apos;{0}&apos; of type &apos;{1}&apos; used in LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ002_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ002_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only property used within LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ002_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ002_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a specific subset of methods are allowed within a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ003_DESC {
            get {
                return ResourceManager.GetString("EFLINQ003_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Static method &apos;{0}&apos; cannot be used within a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ003_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ003_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid static method call within LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ003_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ003_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a specific subset of methods are allowed within a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ004_DESC {
            get {
                return ResourceManager.GetString("EFLINQ004_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; cannot be used within a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ004_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ004_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid method call on instance within LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ004_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ004_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only properties are not translatable to SQL in LINQ to Entities and will cause a NotSupportedException to be thrown by a EF LINQ provider. This is only a warning as the analyzer cannot determine if this LINQ expression is made against an actual DbSet&lt;T&gt;.
        /// </summary>
        internal static string EFLINQ005_DESC {
            get {
                return ResourceManager.GetString("EFLINQ005_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only property &apos;{0}&apos; of type &apos;{1}&apos; potentially used in LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ005_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ005_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read-Only property potentially used within LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ005_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ005_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a specific subset of methods are allowed within a LINQ to Entities expression. This is only a warning as the analyzer cannot determine if this LINQ expression is made against an actual DbSet&lt;T&gt;.
        /// </summary>
        internal static string EFLINQ006_DESC {
            get {
                return ResourceManager.GetString("EFLINQ006_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported static method &apos;{0}&apos; potentially being used within a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ006_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ006_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential invalid static method call within LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ006_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ006_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only a specific subset of methods are allowed within a LINQ to Entities expression. This is only a warning as the analyzer cannot determine if this LINQ expression is made against an actual DbSet&lt;T&gt;.
        /// </summary>
        internal static string EFLINQ007_DESC {
            get {
                return ResourceManager.GetString("EFLINQ007_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported method &apos;{0}&apos; potentially being used within a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ007_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ007_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential unsupported method call on instance within LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ007_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ007_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If using a collection navigation property within a LINQ to Entities expression, be sure to make it a queryable via the AsQueryable() extension method.
        /// </summary>
        internal static string EFLINQ008_DESC {
            get {
                return ResourceManager.GetString("EFLINQ008_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation property &apos;{0}&apos; of type &apos;{1}&apos; within LINQ to Entities expression is not queryable.
        /// </summary>
        internal static string EFLINQ008_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ008_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection navigation property not queryable.
        /// </summary>
        internal static string EFLINQ008_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ008_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If using a collection navigation property within a LINQ to Entities expression, be sure to make it a queryable via the AsQueryable() extension method. This is a warning because the analyzer cannot verify the source of the navigation property access.
        /// </summary>
        internal static string EFLINQ009_DESC {
            get {
                return ResourceManager.GetString("EFLINQ009_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation property &apos;{0}&apos; of type &apos;{1}&apos; within a potential LINQ to Entities expression is not queryable.
        /// </summary>
        internal static string EFLINQ009_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ009_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection navigation property in a potential LINQ to Entities expression is not queryable.
        /// </summary>
        internal static string EFLINQ009_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ009_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If using a collection navigation property within a LINQ to Entities expression, be sure to make it a queryable via the AsQueryable() extension method. This is a warning because the analyzer cannot verify if the given property is truly a navigation property (due to multiple EF model classes having a property with this name) or the source of the navigation property access.
        /// </summary>
        internal static string EFLINQ010_DESC {
            get {
                return ResourceManager.GetString("EFLINQ010_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential navigation property &apos;{0}&apos; within a potential LINQ to Entities expression is not queryable.
        /// </summary>
        internal static string EFLINQ010_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ010_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential collection navigation property in a potential LINQ to Entities expression is not queryable.
        /// </summary>
        internal static string EFLINQ010_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ010_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interpolated string compiles down to a call to String.Format(), which is not translatable to SQL in LINQ to Entities.
        /// </summary>
        internal static string EFLINQ011_DESC {
            get {
                return ResourceManager.GetString("EFLINQ011_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interoplated string cannot be used in a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ011_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ011_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interoplated string cannot be used in a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ011_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ011_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An interpolated string compiles down to a call to String.Format(), which is not translatable to SQL in LINQ to Entities. This is only a warning as the analyzer cannot determine if this LINQ expression is made against an actual DbSet&lt;T&gt;.
        /// </summary>
        internal static string EFLINQ012_DESC {
            get {
                return ResourceManager.GetString("EFLINQ012_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interoplated string potentially used in a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ012_MSGFORMAT {
            get {
                return ResourceManager.GetString("EFLINQ012_MSGFORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interoplated string potentially used in a LINQ to Entities expression.
        /// </summary>
        internal static string EFLINQ012_TITLE {
            get {
                return ResourceManager.GetString("EFLINQ012_TITLE", resourceCulture);
            }
        }
    }
}
